version: '3.7'

services:
  sail-mockapi:
    image: sail-mockapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/src